matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      env: TRAVIS_XCODE_VERSION=82
    - os: osx
      osx_image: xcode8.1
      env: TRAVIS_XCODE_VERSION=81
    - os: osx
      osx_image: xcode8
      env: TRAVIS_XCODE_VERSION=8
    - os: osx
      osx_image: xcode7.3
      env: TRAVIS_XCODE_VERSION=73
install:
  - bundle install
  - rake
script:
  - rake test
notifications:
  email: false
