require 'English'
require 'fileutils'
require 'colorize'
require 'inquirer'
require_relative 'version'
require_relative 'plugins_updater'
require_relative 'xcode_unsigner'
require_relative 'launch_agent'
